spring.data.mongodb.uri=mongodb+srv://moosaviqar2005_db_user:CloudShare123@cloudshare.1xwunj1.mongodb.net/CloudShare?retryWrites=true&w=majority&appName=CloudShare


logging.level.org.springframework.data.mongodb=DEBUG

server.servlet.context-path=/api/v1.0

spring.data.mongodb.auto-index-creation=true


spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

clerk.issuer=https://magnetic-finch-60.clerk.accounts.dev
clerk.jwks-url=https://magnetic-finch-60.clerk.accounts.dev/.well-known/jwks.json

clerk.webhook.secret=wbfjVvh1XJUd2QY0Hqfe1ooB+9d98XBI

#file upload configuration
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=25MB
